#set logging level because of bug in swagger-models dependency
#it is already fixed but springfox hasn't released their project with the new dependency
logging:
  level:
    io:
      swagger:
        models:
          parameters:
           AbstractSerializableParameter: ERROR

#DB configuration
spring:
  datasource:
    url: jdbc:h2:mem:mytaxi_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    
