
create table if not exists car (
        id bigint generated by default as identity,
        date_created timestamp not null,
        deleted boolean not null,
        engine_type varchar(255),
        license_plate varchar(255),
        rating float,
        seat_count integer,
        manufacturer varchar(255),
        convertible boolean,
        color varchar(255),
        model varchar(255),
        primary key (id)
    );


create table if not exists DRIVER (
    id bigint generated by default as identity,
    coordinate binary(255),
    date_coordinate_updated timestamp,
    date_created timestamp not null,
    deleted boolean not null,
    online_status varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

 create table if not exists driver_car (
        id bigint generated by default as identity,
        car_id bigint,
        driver_id bigint,
        primary key (id)
    );